blueprints/About.py
from flask import *

about = Blueprint('about', __name__)


@about.route('/about')
def about_page():
    """"About page"""
    return render_template('about.html')


@about.route('/contact/')
def contact():
    """Contact page"""
    return render_template('contact.html')

blueprints/add.py
from flask import Blueprint, url_for, render_template, request, flash
from flask import *
from flask_login import login_required

from models.database import db
from models.Category import Category
from models.Item import Item


add = Blueprint('add', __name__)


@add.route('/add')
@login_required
def admin_add():
    """Add a new item to the database"""
    categories = Category.query.all()
    return render_template('add.html', categories=categories)


@add.route('/remove')
@login_required
def remove():
    """Remove an item in the marketplace"""
    data = Item.query.filter_by(Item.id)
    return render_template('remove.html', data=data)


@add.route('/removeItem')
def remove_item():
    """Remove an item in the marketplace"""
    item_id = request.args.get('Item.id')
    try:
        item_id = Item.query.filter(Item.id == item_id).first()
        db.session.delete(item_id)
        db.session.commit()
        flash('Successfully removed item', 'success')
    except:
        flash('Failed to remove item.', 'danger')
        return redirect(url_for('/remove'))
    return redirect(url_for('/remove'))


@add.route('/category')
@login_required
def category():
    return render_template('addcategory.html')


@add.route('/addCategory', methods=['POST'])
def addCategory():
    """Add a new category to the database"""
    if request.method == 'POST':
        name = request.form.get('name')

        new_category = Category(name=name)
        old_category = Category.query.filter(Category.name == name).first()
        try:
            db.session.add(new_category)
            db.session.commit()
            flash('Added new category', 'success')
            return redirect('/')
        except:
            if old_category:
                flash('Error adding category', 'error')
                return "That category already exists. Please try again"
                return redirect(url_for('/category'))

blueprints/auth.py
import smtplib
from flask import *
from flask_login import login_user, logout_user, current_user
from random_password import random_password

from models.user import User
from werkzeug.security import check_password_hash, generate_password_hash
from models.database import db
from flask_mail import Message

auth = Blueprint('auth', __name__)


@auth.route('/login')
def login():
    """login method"""
    return render_template('login.html')


@auth.route('/login', methods=['POST'])
def login_post():
    """login method"""
    username = request.form.get('username')
    password = request.form.get('password')
    remember = True if request.form.get('remember') else False

    user = User.query.filter_by(username=username).first()
    if not user:
        flash('You are not registered. Please signup now.', 'danger')
        return redirect(url_for('auth.signup_post'))
    elif not check_password_hash(user.password, password):
        flash('Please check your login details and try again.', 'danger')
        return redirect(url_for('auth.login'))
    else:
        login_user(user, remember=remember)
        flash('You have successfully logged in', 'success')
        return redirect(url_for('index'))


@auth.route('/signup')
def signup():
    """signup method"""
    return render_template('signup.html')


@auth.route('/signup', methods=['POST'])
def signup_post():
    """signup method"""
    username = request.form.get('username')
    email = request.form.get('email')
    password = request.form.get('password')
    confirm_password = request.form.get('confirm_password')

    if password != confirm_password:
        flash('passwords do not match!', category='danger')
        return redirect(url_for('auth.signup'))

    if len(password) < 4 or len(confirm_password) < 4:
        flash('Passwords must be at least 4 characters.', category='danger')
        return redirect(url_for('auth.signup'))

    user = User.query.filter_by(email=email).first()
    userName = User.query.filter_by(username=username).first()
    new_user = User(username=username, email=email, password=generate_password_hash(password, method='sha256'))
    if user or userName:
        flash('You are already registered!', 'danger')
        return redirect(url_for('auth.login'))
    else:
        db.session.add(new_user)
        db.session.commit()
        flash('You have been registered!', category='success')
        return redirect(url_for('auth.login'))


@auth.route('/logout')
def logout():
    logout_user()
    session.clear()
    return redirect(url_for('auth.login'))


@auth.route('/reset_password')
def reset_password():
    return render_template('reset_password.html')


@auth.route('/reset_password', methods=['POST'])
def reset_password_post():
    email = request.form.get('email')
    user = User.query.filter_by(email=email).first()
    if current_user.is_authenticated:
        return redirect(url_for('index'))
    if not user:
        flash('User email does not exist', 'danger')
        return redirect(url_for('auth.reset_password'))
    token = random_password()
    user.password = generate_password_hash(token, method='sha256')
    db.session.commit()

    msg = Message('Password Reset Request',
                  sender='meshack3197@gmail.com',
                  recipients='meshack3197@gmail.com')
    msg.body = f'To reset your password, Use this temporary token: {token}'
    try:
        smtpObj = smtplib.SMTP('localhost')
        smtpObj.sendmail(msg)
        flash('An email has been sent with instructions to reset your password', 'success')
    except smtplib.SMTPException:
        flash("Error: unable to send email", 'danger')
    return redirect(url_for('auth.login'))

blueprints/cart.py
from flask import *
from flask_login import current_user, login_required

from models.database import db
from models.user import User
from models.Item import Item
from models.CartItem import CartItem

cart = Blueprint('cart', __name__)


@cart.route('/addToCart/<int:item_id>/<int:user_id>')
@login_required
def addToCart(item_id, user_id):
    """Add an item to the cart"""
    new_item = CartItem(user_id=user_id, item_id=item_id)
    try:
        db.session.add(new_item)
        db.session.commit()
        flash('added successfully to cart', 'success')
    except:
        db.session.rollback()
        flash('Error adding new item', 'danger')
    return redirect(url_for('index'))


@cart.route('/cart', methods=['GET', 'POST'])
@login_required
def to_cart():
    """display items in the cart"""
    itemData = Item.query.filter(Item.id == CartItem.item_id and current_user.id == CartItem.user_id).all()
    count = CartItem.query.filter(Item.id == CartItem.item_id and current_user.id == CartItem.user_id).count()
    subtotal = 0
    for item in itemData:
        subtotal += item.price
    if count == 0:
        flash('No cart items available to purchase.', 'danger')
        return redirect(url_for('index'))
    return render_template('cart.html', itemData=itemData, subtotal=subtotal, count=count)


@cart.route('/removeFromCart')
def removeFromCart():
    """Route to  remove an item from the cart."""
    user_id = CartItem.query.filter(current_user.id == User.id).first()
    try:
        db.session.delete(user_id)
        db.session.commit()
        flash('Successfully removed item', 'success')
    except:
        flash('Error removing item')
    return redirect(url_for('cart.to_cart'))

blueprints/categories.py
from flask import *
from models.Item import Item
from models.Category import Category

category = Blueprint('category', __name__)


@category.route('/itemDescription/<int:item_id>')
def itemDescription(item_id):
    """Item description route"""
    itemData = Item.query.filter(Item.id == item_id).first()
    return render_template('itemDescription.html', itemData=itemData)


@category.route('/men')
def men():
    """
    :return: route to men products
    """
    categoryName = Category.query.filter(Category.id == '2').first()
    items = Item.query.filter(Item.categoryId == '2').all()
    return render_template('men.html', items=items, categoryName=categoryName)


@category.route('/women')
def women():
    """
    :return: route to '/women' products
    """
    categoryName = Category.query.filter(Category.id == '1').first()
    items = Item.query.filter(Item.categoryId == '1').all()
    return render_template('women.html', items=items, categoryName=categoryName)

blueprints/profile.py
import hashlib
from crypt import methods

from flask import *
from flask_login import login_required, current_user, fresh_login_required
from werkzeug.security import generate_password_hash, check_password_hash

from models.user import User
from models.database import db

profile = Blueprint('profile', __name__)


@profile.route('/account/profile')
def account_profile():
    return render_template('profile.html')


@profile.route('/account/profile/edit')
@login_required
def account_profile_edit():
    """edit profile"""
    return render_template('editProfile.html')


@profile.route('/account/profile/update', methods=['GET', 'POST'])
@login_required
def account_profile_update():
    """update profile"""
    if request.method == 'POST':
        username = request.form.get('username')
        email = request.form.get('email')
        try:
            new_user = User(username=username, email=email)
            db.session.add(new_user)
            db.session.commit()
            flash('Profile updated successfully', 'success')
        except:
            db.session.rollback()
            flash('Profile update failed!', 'danger')
        return redirect(url_for('profile.account_profile'))


@profile.route('/account/profile/change', methods=['GET', 'POST'])
@login_required
def change_p():
    return render_template('changepassword.html')


@profile.route('/account/profile/changePassword', methods=['GET', 'POST'])
@login_required
def change_password():
    """change password"""
    if request.method == 'POST':
        oldpassword = request.form.get('oldpassword')
        newpassword = request.form.get('newpassword')
        newpassword1 = request.form.get('newpassword1')

        user = User.query.filter(User.id == current_user.id).first()
        if oldpassword == newpassword:
            flash('New password should be different from previous password', 'danger')
            return redirect(url_for('profile.change_p'))
        if len(newpassword) < 4 or len(newpassword1) < 4:
            flash('Passwords must be at least 4 characters.', category='danger')
            return redirect(url_for('profile.change_p'))
        if newpassword != newpassword1:
            flash('Your new passwords do not match!', category='danger')
            return redirect(url_for('profile.change_p'))
        if check_password_hash(user.password, oldpassword):
            user.password = generate_password_hash(newpassword, method='sha256')
            db.session.commit()
            flash('Password changed successfully.', 'success')
            return redirect(url_for('auth.logout'))
        else:
            flash('wrong password', 'danger')
            return redirect(url_for('profile.change_p'))
    else:
        flash('Something went wrong', 'danger')
        return 'Something went wrong'


@profile.route('/wishlist', methods=['GET', 'POST'])
def wishlist():
    """ Wish list method """
    return render_template('add-to-wishlist.html')

templates/add-to-wishlist.html
{% extends 'base.html' %}
{% block content %}
<div class="colorlib-loader"></div>

<div id="page">
    <div class="breadcrumbs">
        <div class="container">
            <div class="row">
                <div class="col">
                    <p class="bread"><span><a href="index.html">Home</a></span> / <span>My Wishlist</span></p>
                </div>
            </div>
        </div>
    </div>


    <div class="colorlib-product">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 offset-sm-2 text-center colorlib-heading colorlib-heading-sm">
                    <h2>Shop more</h2>
                </div>
            </div>
            <div class="row">
                <div class="col-md-3 col-lg-3 mb-4 text-center">
                    <div class="product-entry border">
                        <a href="#" class="prod-img">
                            <img src="static/images/item-1.jpg" class="img-fluid" alt="Free html5 bootstrap 4 template">
                        </a>
                        <div class="desc">
                            <h2><a href="#">Women's Boots Shoes Maca</a></h2>
                            <span class="price">$139.00</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 mb-4 text-center">
                    <div class="product-entry border">
                        <a href="#" class="prod-img">
                            <img src="static/images/item-2.jpg" class="img-fluid" alt="Free html5 bootstrap 4 template">
                        </a>
                        <div class="desc">
                            <h2><a href="#">Women's Minam Meaghan</a></h2>
                            <span class="price">$139.00</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 mb-4 text-center">
                    <div class="product-entry border">
                        <a href="#" class="prod-img">
                            <img src="static/images/item-3.jpg" class="img-fluid" alt="Free html5 bootstrap 4 template">
                        </a>
                        <div class="desc">
                            <h2><a href="#">Men's Taja Commissioner</a></h2>
                            <span class="price">$139.00</span>
                        </div>
                    </div>
                </div>
                <div class="col-md-3 col-lg-3 mb-4 text-center">
                    <div class="product-entry border">
                        <a href="#" class="prod-img">
                            <img src="static/images/item-4.jpg" class="img-fluid" alt="Free html5 bootstrap 4 template">
                        </a>
                        <div class="desc">
                            <h2><a href="#">Russ Men's Sneakers</a></h2>
                            <span class="price">$139.00</span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock content %}

templates/index.html
{% extends 'base.html' %}
{% block content %}

<div class="colorlib-loader"></div>

<div id="page">

    <aside id="colorlib-hero">
        <div class="flexslider">
            <ul class="slides">
                <li style="background-image: url(/static/images/img_bg_1.jpg);">
                    <div class="overlay"></div>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6 offset-sm-3 text-center slider-text">
                                <div class="slider-text-inner">
                                    <div class="desc">
                                        <h1 class="head-1">Men's</h1>
                                        <h2 class="head-2">Shoes</h2>
                                        <h2 class="head-3">Collection</h2>
                                        <p class="category"><span>New trending shoes!</span></p>
                                        <p><a href="#shopall" class="btn btn-primary smoothScroll">Shop Collection</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li style="background-image: url(/static/images/img_bg_2.jpg);">
                    <div class="overlay"></div>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6 offset-sm-3 text-center slider-text">
                                <div class="slider-text-inner">
                                    <div class="desc">
                                        <h1 class="head-1">Big</h1>
                                        <h2 class="head-2">Sale</h2>
                                        <h2 class="head-3"><strong class="font-weight-bold">20%</strong> Off</h2>
                                        <p class="category"><span>Huge sale sandals</span></p>
                                        <p><a href="#shopall" class="btn btn-primary smoothScroll">Shop Collection</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
                <li style="background-image: url(/static/images/img_bg_3.jpg);">
                    <div class="overlay"></div>
                    <div class="container-fluid">
                        <div class="row">
                            <div class="col-sm-6 offset-sm-3 text-center slider-text">
                                <div class="slider-text-inner">
                                    <div class="desc">
                                        <h1 class="head-1">New</h1>
                                        <h2 class="head-2">Arrivals</h2>
                                        <h2 class="head-3">up to <strong class="font-weight-bold">30%</strong> off
                                        </h2>
                                        <p class="category"><span>New Fashion shoes for men</span></p>
                                        <p><a href="#shopall" class="btn btn-primary smoothScroll">Shop Collection</a>
                                        </p>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </li>
            </ul>
        </div>
    </aside>
    <div class="colorlib-intro">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h2 class="intro">Get your favourite and Quality footwear from World's best Online Shoe Store .
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="colorlib-product">
        <div class="container-fluid">
            <div class="row">
                <div class="col-sm-6 text-center">
                    <div class="featured">
                        <a href="/men" class="featured-img"
                           style="background-image: url(/static/images/men.jpg);"></a>
                        <div class="desc">
                            <h2><a href="/men">Shop Men's Collection</a></h2>
                        </div>
                    </div>
                </div>
                <div class="col-sm-6 text-center">
                    <div class="featured">
                        <a href="/women" class="featured-img"
                           style="background-image: url(/static/images/women.jpg);"></a>
                        <div class="desc">
                            <h2><a href="/women">Shop Women's Collection</a></h2>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <div class="colorlib-product">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 offset-sm-2 text-center colorlib-heading" id="shopall">
                    <h2>Shop All Products</h2>
                </div>
            </div>
            <div class="display">
                <div class="row row-pb-md">
                    <div class="mw-100"></div>
                    {% for data in items.items %}
                    <div class="col-lg-3 mb-4 text-center">
                        <div class="product-entry border">
                            <a href="{{ url_for('category.itemDescription', item_id= data.id) }}" class="prod-img">
                                <img src={{url_for('static' , filename='images/' + data.image)}}
                                     class="img-fluid" alt="IMAGE">
                            </a>
                            <div class="desc">
                                <h2>
                                    <a href="{{ url_for('category.itemDescription', item_id= data.id) }}">{{data.name}}</a>
                                </h2>
                                <span class="icon-price-tag"> ${{data.price}}</span>
                            </div>
                            <div class="cart mt-4 align-items-left">
                                {% if current_user.is_authenticated%}
                                <button class="btn btn-outline-secondary mr-2 px-4 align-content-lg-start">
                                    <a href="{{url_for('cart.addToCart', item_id=data.id, user_id=current_user.id) }}">
                                        Add to cart
                                    </a>
                                </button>
                                {% endif %}
                                {% if current_user.is_authenticated and current_user.usertype_id ==1 %}

                                <button class="btn btn-btn-primary btn-outline-danger  mr-2 px-4 align-content-lg-end">

                                    <a href="{{url_for('removeItem', item_id = data.id)}}">
                                        Delete
                                    </a>
                                    <i class='fas fa-trash-alt'></i>
                                </button>
                                {% endif %}
                                <i class="fa fa-heart text-muted"></i>
                                <i class="fa fa-share-alt text-muted"></i>
                            </div>
                        </div>

                    </div>
                    {% endfor %}
                </div>
            </div>
            <!-- pagination links-->
            <div class="text-center">
                <a href="{{ url_for('index', page=items.prev_num) }}"
                   class="btn btn-outline-dark
       {% if items.page == 1 %}disabled{% endif %}">
                    &laquo;
                </a>
                <!-- Loop through the number of pages to display a link for each-->
                {% for page_num in items.iter_pages(left_edge=1, right_edge=1, left_current=1, right_current=2) %}
                {% if page_num %}
                <!-- Check for the active page and set the link to "Active"-->
                {% if items.page == page_num %}
                <a href="{{ url_for('index', page=page_num) }}"
                   class="btn btn-dark">
                    {{ page_num }}
                </a>
                {% else %}
                <a href="{{ url_for('index', page=page_num) }}"
                   class="btn btn-outline-dark">
                    {{ page_num }}
                </a>
                {% endif %}
                {% else %}
                ...
                {% endif %}
                {% endfor %}
                <a href="{{ url_for('index', page=items.next_num) }}"
                   class="btn btn-outline-dark
       {% if items.page == items.pages %}disabled{% endif %}">
                    &raquo;
                </a>
            </div>
            <b><p class="text-right mt-4">
                Showing page {{ items.page }} of {{ items.pages }}
            </p>
            </b>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p><a href="#shopall" class="btn btn-primary btn-lg">Shop All Products</a></p>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/men.html
{% extends 'base.html' %}
{% block content %}

<div class="colorlib-loader"></div>
<div id="page">
    <div class="colorlib-intro">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h2 class="intro">Get your favourite and Quality footwear from World's best Online Shoe Store .
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="colorlib-product">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 offset-sm-2 text-center colorlib-heading">
                    <h2>{{categoryName.name}} Products </h2>
                </div>
            </div>
            <div class="display">
                <div class="row row-pb-md">
                    <div class="mw-100"></div>
                    {% for data in items %}
                    <div class="col-lg-3 mb-4 text-center">
                        <div class="product-entry border">
                            <a href="{{ url_for('category.itemDescription', item_id= data.id) }}" class="prod-img">
                                <img src={{url_for('static' , filename='images/' + data.image)}}
                                     class="img-fluid" alt="IMAGE">
                            </a>
                            <div class="desc">
                                <h2><a href="{{ url_for('category.itemDescription', item_id= data.id) }}">{{data.name}}</a></h2>
                                <span class="price">${{data.price}}</span>
                            </div>

                    <div class="cart mt-4 align-items-left">
                        {% if current_user.is_authenticated%}
                        <button class="btn btn-outline-secondary mr-2 px-4 align-content-lg-start">

                            <a href="{{url_for('cart.addToCart', item_id=data.id, user_id=current_user.id) }}">
                                Add to cart
                            </a>

                        </button>
                        {% endif %}
                        {% if current_user.is_authenticated and current_user.usertype_id ==1 %}

                        <button class="btn btn-btn-primary btn-outline-danger  mr-2 px-4 align-content-lg-end">

                            <a href="{{url_for('removeItem', item_id = data.id)}}">
                                Delete
                            </a>
                            <i class='fas fa-trash-alt'></i>
                        </button>
                        {% endif %}
                        <i class="fa fa-heart text-muted"></i>
                        <i class="fa fa-share-alt text-muted"></i>
                    </div>
                            </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p><a href="/.#shopall" class="btn btn-primary btn-lg">Shop All Products</a></p>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}

templates/reset_password.html
{% extends 'base.html' %}
{% block content %}
<div class="row justify-content-center">
<div class="col-xl-10">
    <div class="text-center">
        <h1 class="h4 text-gray-900 mb-2">Forgot Your Password?</h1>
        <p class="mb-4">We get it, stuff happens. Just enter your email address below
            and we'll send you a new temporary password!</p>
    </div>
    <form class="user" action="{{ url_for('auth.reset_password_post') }}" method="post">
        <div class="form-group">
            <input type="email" class="form-control form-control-user"
                   id="email" name="email" aria-describedby="emailHelp"
                   placeholder="Enter Email Address...">
        </div>
        <button type="submit" class="btn btn-primary btn-user btn-block">
            Reset Password
        </button>
    </form>
    <hr>
    <div class="text-center">
        <a class="small" href="{{ url_for('auth.login') }}">Already have an account?
            Log in here!</a>
    </div>
</div>
</div>

{% endblock content %}

templates/women.html
{% extends 'base.html' %}
{% block content %}

<div class="colorlib-loader"></div>
<div id="page">
    <div class="colorlib-intro">
        <div class="container">
            <div class="row">
                <div class="col-sm-12 text-center">
                    <h2 class="intro">Get your favourite and Quality footwear from World's best Online Shoe Store .
                    </h2>
                </div>
            </div>
        </div>
    </div>
    <div class="colorlib-product">
        <div class="container">
            <div class="row">
                <div class="col-sm-8 offset-sm-2 text-center colorlib-heading">
                    <h2>{{categoryName.name}} Products </h2>
                </div>
            </div>
            <div class="display">
                <div class="row row-pb-md">
                    <div class="mw-100"></div>
                    {% for data in items %}
                    <div class="col-lg-3 mb-4 text-center">
                        <div class="product-entry border">
                            <a href="{{ url_for('category.itemDescription', item_id= data.id) }}" class="prod-img">
                                <img src={{url_for('static' , filename='images/' + data.image)}}
                                     class="img-fluid" alt="IMAGE">
                            </a>
                            <div class="desc">
                                <h2><a href="{{ url_for('category.itemDescription', item_id= data.id) }}">{{data.name}}</a></h2>
                                <span class="price">${{data.price}}</span>
                            </div>

                    <div class="cart mt-4 align-items-left">
                        {% if current_user.is_authenticated%}
                        <button class="btn btn-outline-secondary mr-2 px-4 align-content-lg-start">

                            <a href="{{url_for('cart.addToCart', item_id=data.id, user_id=current_user.id) }}">
                                Add to cart
                            </a>

                        </button>
                        {% endif %}
                        {% if current_user.is_authenticated and current_user.usertype_id ==1 %}

                        <button class="btn btn-btn-primary btn-outline-danger  mr-2 px-4 align-content-lg-end">

                            <a href="{{url_for('removeItem', item_id = data.id)}}">
                                Delete
                            </a>
                            <i class='fas fa-trash-alt'></i>
                        </button>
                        {% endif %}
                        <i class="fa fa-heart text-muted"></i>
                        <i class="fa fa-share-alt text-muted"></i>
                    </div>
                            </div>
                    </div>
                    {% endfor %}
                </div>
            </div>
            <div class="row">
                <div class="col-md-12 text-center">
                    <p><a href="/.#shopall" class="btn btn-primary btn-lg">Shop All Products</a></p>
                </div>
            </div>
        </div>
    </div>

</div>
{% endblock content %}